### ISSUE TITLE
[CHORE] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by leeeyubin** [NOW-SOPT-APP6-BUBBLE/bubble-Android#1]
### ☑️Github 설정

- [x]  branch rule 추가 (approve, lock)
- [x]  issue 템플릿
- [x]  pull request 템플릿
- [x]  label 추가
- [ ]  description 추가

### ☑️Android Studio 설정

- [x]  gradle 기초 세팅
- [x]  manifest 인터넷 권한 추가, 트래픽 설정, 화면 회전 방지
- [x]  application 추가
- [x]  더미 파일 생성
- [x]  색상 추가
- [x]  타이포 추가

**Comment by arinming** [comment]
👍🏻✨😍
